structure(list(url = "http://geowb.worldbank.org/bears", status_code = 404L, 
    headers = structure(list(`content-type` = "text/html", server = "Microsoft-IIS/7.5", 
        `x-powered-by` = "ASP.NET", date = "Mon, 11 Jun 2018 21:18:21 GMT", 
        `content-length` = "1245"), .Names = c("content-type", 
    "server", "x-powered-by", "date", "content-length"), class = c("insensitive", 
    "list")), all_headers = list(structure(list(status = 404L, 
        version = "HTTP/1.1", headers = structure(list(`content-type` = "text/html", 
            server = "Microsoft-IIS/7.5", `x-powered-by` = "ASP.NET", 
            date = "Mon, 11 Jun 2018 21:18:21 GMT", `content-length` = "1245"), .Names = c("content-type", 
        "server", "x-powered-by", "date", "content-length"), class = c("insensitive", 
        "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = logical(0), flag = logical(0), 
        path = logical(0), secure = logical(0), expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n"), 
    date = structure(1528751901, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 0.016, 0.016, 0.016, 
    0.016, 0.016), .Names = c("redirect", "namelookup", "connect", 
    "pretransfer", "starttransfer", "total")), request = structure(list(
        method = "GET", url = "http://geowb.worldbank.org/bears", 
        headers = structure("application/json, text/xml, application/xml, */*", .Names = "Accept"), 
        fields = NULL, options = structure(list(useragent = "libcurl/7.59.0 r-curl/3.2 httr/1.3.1", 
            cainfo = "C:/PROGRA~1/R/R-34~1.3/etc/curl-ca-bundle.crt", 
            httpget = TRUE), .Names = c("useragent", "cainfo", 
        "httpget")), output = structure(list(), class = c("write_memory", 
        "write_function"))), .Names = c("method", "url", "headers", 
    "fields", "options", "output"), class = "request")), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times", "request"), class = "response")
