structure(list(url = "https://datacatalog.worldbank.org/services/session/token", 
    status_code = 200L, headers = structure(list(date = "Mon, 11 Jun 2018 19:26:03 GMT", 
        server = "Apache/2.2.15 (Red Hat)", `x-content-type-options` = "nosniff", 
        `x-powered-by` = "PHP/5.6.30", expires = "Sun, 19 Nov 1978 05:00:00 GMT", 
        `cache-control` = "no-cache, must-revalidate", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding,User-Agent", `content-encoding` = "gzip", 
        `content-length` = "63", connection = "close", `content-type` = "text/plain;charset=UTF-8"), .Names = c("date", 
    "server", "x-content-type-options", "x-powered-by", "expires", 
    "cache-control", "x-content-type-options", "vary", "content-encoding", 
    "content-length", "connection", "content-type"), class = c("insensitive", 
    "list")), all_headers = list(structure(list(status = 200L, 
        version = "HTTP/1.1", headers = structure(list(date = "Mon, 11 Jun 2018 19:26:03 GMT", 
            server = "Apache/2.2.15 (Red Hat)", `x-content-type-options` = "nosniff", 
            `x-powered-by` = "PHP/5.6.30", expires = "Sun, 19 Nov 1978 05:00:00 GMT", 
            `cache-control` = "no-cache, must-revalidate", `x-content-type-options` = "nosniff", 
            vary = "Accept-Encoding,User-Agent", `content-encoding` = "gzip", 
            `content-length` = "63", connection = "close", `content-type` = "text/plain;charset=UTF-8"), .Names = c("date", 
        "server", "x-content-type-options", "x-powered-by", "expires", 
        "cache-control", "x-content-type-options", "vary", "content-encoding", 
        "content-length", "connection", "content-type"), class = c("insensitive", 
        "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = c("datacatalog.worldbank.org", 
    "#HttpOnly_.datacatalog.worldbank.org"), flag = c(FALSE, 
    TRUE), path = c("/", "/"), secure = c(FALSE, TRUE), expiration = structure(c(Inf, 
    1548745162), class = c("POSIXct", "POSIXt")), name = c("datacatalog.sfarm", 
    "SSESSea72a4c978dd1670e2b2d8df72f13a23"), value = c("REDACTED", 
    "REDACTED")), .Names = c("domain", "flag", "path", "secure", 
    "expiration", "name", "value"), row.names = c(NA, -2L), class = "data.frame"), 
    content = as.raw(c(0x56, 0x4c, 0x32, 0x42, 0x48, 0x58, 0x69, 
    0x53, 0x73, 0x2d, 0x41, 0x4f, 0x45, 0x6e, 0x72, 0x76, 0x6f, 
    0x4e, 0x74, 0x4f, 0x36, 0x4b, 0x59, 0x56, 0x77, 0x70, 0x6f, 
    0x57, 0x41, 0x41, 0x58, 0x69, 0x6e, 0x56, 0x73, 0x44, 0x75, 
    0x57, 0x6a, 0x39, 0x64, 0x6f, 0x59)), date = structure(1528745163, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 1e-06, 
    1e-06, 0.016, 0.516, 0.985), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total")), request = structure(list(
        method = "POST", url = "https://datacatalog.worldbank.org/services/session/token", 
        headers = structure(c("", "application/json", "SSESSea72a4c978dd1670e2b2d8df72f13a23=pvdDY9OO5otutw4tvQFT225tA9DsmWEv6YFTIrU8OgA"
        ), .Names = c("Content-Type", "Accept", "Cookie")), fields = NULL, 
        options = structure(list(useragent = "libcurl/7.59.0 r-curl/3.2 httr/1.3.1", 
            cainfo = "C:/PROGRA~1/R/R-34~1.3/etc/curl-ca-bundle.crt", 
            post = TRUE, postfieldsize = 0L), .Names = c("useragent", 
        "cainfo", "post", "postfieldsize")), output = structure(list(), class = c("write_memory", 
        "write_function"))), .Names = c("method", "url", "headers", 
    "fields", "options", "output"), class = "request")), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times", "request"), class = "response")
